(cram
 (applies_to visibility)
 (deps
  %{bin:cavoc-explore_cli}
  no-visible-flag/no-visible-flag.ml
  no-visible-flag/no-visible-flag.mli
  while/while.ml))

(cram
 (applies_to interaction)
 (deps
  %{bin:cavoc-explore_cli}
  private_counter/private_counter.ml
  private_counter/private_counter.mli))

(cram
 (applies_to composition)
 (deps
  %{bin:cavoc-explore_cli}
  compose/module.ml
  compose/module.mli
  compose/client.ml
  compose/client.mli
  vending-till/till.ml
  vending-till/till.mli
  vending-till/vending.ml
  vending-till/vending.mli
  twice-iter2/twice.ml
  twice-iter2/twice.mli
  twice-iter2/iter2.ml
  twice-iter2/iter2.mli
  polymorphic-compose/identity.ml
  polymorphic-compose/identity.mli
  polymorphic-compose/forward.ml
  polymorphic-compose/forward.mli))
