name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OCaml and Dune
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: 5.0.0
          dune-version: 3.9.0

      - name: Install js_of_ocaml
        run: opam install js_of_ocaml js_of_ocaml-lwt -y

      - name: Build the Project
        run: dune build

      - name: Run Tests
        run: dune runtest
