name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.0 # Remplacez par la version appropriée
        dune-cache: true

    - name: Install dependencies
      run: |
        opam install . --deps-only --yes

    - name: Build all executables
      run: dune build @install

    - name: Build JavaScript for explore_web
      run: dune build _build/default/bin/explore_web.bc.js

    - name: Run tests with dune
      run: dune exec ./_build/default/bin/explore.exe test/isc.ml test/isc.mli